name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # Every 6 hours
    - cron: "0 */6 * * *"
  # Allows the action to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository so your job can access it
      - uses: actions/checkout@v3  # Updated to the latest stable version

      # Step 2: Generate the snake contribution graph
      - uses: Platane/snk@v2.0.0
        id: snake-gif
        with:
          github_user_name: armahah23  # Replace with your GitHub username

      # Step 3: Show the status of the build for debugging purposes
      - run: git status

      # Step 4: Push the changes to the repository
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0  # Pinned to a stable version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output  # Change to "main" or "master" if that is your default branch
          force: true

      # Step 5: Deploy the output to GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
